POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QwMkBleGFtcGxlLmNvbSIsImV4cCI6MTc0MDYyMDcyNywidXNlcklkIjowfQ.j-Cq8Y3eqiWJwlVbgnlgi_K_O0dp8KLJti_EB5POCmE

{

    "Name": "Test event 50",
    "Description": "Test description for event",
    "Location": "Test location",
    "DateTime": "2024-04-13T08:30:00Z"

}