DELETE http://localhost:8080/events/3
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QwMkBleGFtcGxlLmNvbSIsImV4cCI6MTc0MDYyMDg3NiwidXNlcklkIjowfQ.fioVcLECuG_KO9BEvc5KCDjo-f-KuDU3lU6vslj6ukE