name: Docker Image CI

on:
  push:
    branches: [ "development" ]

env:
  DOCKER_IMAGE_NAME: my-docker-image
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Create JSON manifest
      run: |
          echo '{
            "database_server_host": "${{ secrets.DATABASE_SERVER_HOST }}",
            "database_server_port": "5432",
            "database": "postgres",
            "db_user": "postgres",
            "db_password": ""
          }' > manifest.json
      shell: bash
    - name: Print manifest
      run: cat manifest.json;ls -al
      shell: bash
      
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
