name: Docker Image CI

on:
  push:
    branches: [ "development" ]

env:
  DOCKER_IMAGE_NAME: my-docker-image
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Create JSON manifest
      run: |
          echo '{
            "version": "${{ github.sha }}",
            "build_date": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "repository": "${{ github.repository }}"
          }' > manifest.json
      shell: bash
      
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
